version: '3.8'

services:
  tia-carmen-recipes:
    build: .
    container_name: tia-carmen-recipes-dev
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./recipes:/app/recipes
      - ./templates:/app/templates
      - ./static:/app/static
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s