version: '3.8'

services:
  tia-carmen-recipes:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tia-carmen-recipes
    ports:
      - "5014:5014"
    # volumes:
    #   - ./data:/app/data
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
      - FLASK_PORT=5014
      # - DATABASE_PATH=/app/data/recipes.db
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5014/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: gelf
      options:
        gelf-address: "udp://host.docker.internal:12201"
        tag: "tia-carmen-recipes"
        labels: "service,environment"
        env: "FLASK_ENV,FLASK_PORT"

  # Optional: Add nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: tia-carmen-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - tia-carmen-recipes
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    profiles:
      - production
    logging:
      driver: gelf
      options:
        gelf-address: "udp://host.docker.internal:12201"
        tag: "tia-carmen-nginx"
        labels: "service"